# Configurations
ip: "192.168.1.100"
domain: "elpixeler.com"
xampp:
  version: '7.4.2'
mysql:
  root_password: Ch@nge_ME_2Something$ecure
dns_server:
  setup: true
wordpress:
  install: true
  db_user: wp_admin
  db_password: Ch@nge_ME_2Something$ecure